# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Valtrainer.ValTrainer
PackageVersion: 1.4.1
InstallerLocale: en-US
MinimumOSVersion: 10.0.14393.0
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{8BC1A72E-9D6C-4649-AE20-032F14D7A1F5}_is1'
ReleaseDate: 2026-10-03
AppsAndFeaturesEntries:
- DisplayName: ValTrainer
  Publisher: ValTrainer contributors
  ProductCode: '{8BC1A72E-9D6C-4649-AE20-032F14D7A1F5}_is1'
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/idoraz1/ValTrainer/releases/download/v1.4.1/ValTrainer-1.4.1-Setup.exe
  InstallerSha256: 97BD7B5819CE3CB516C8C17ACD594CEB162886C23140C4852EFD81048EB4C43D
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/idoraz1/ValTrainer/releases/download/v1.4.1/ValTrainer-1.4.1-Setup.exe
  InstallerSha256: 97BD7B5819CE3CB516C8C17ACD594CEB162886C23140C4852EFD81048EB4C43D
  InstallerSwitches:
    Custom: /ALLUSERS
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
